version: '3.8'

services:
  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./src/frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend

  backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./src/backend:/app
    environment:
      - ENVIRONMENT=development
      - MODEL_PATH=/app/models/fraud_model.pkl
      - ALLOWED_ORIGINS=http://localhost:3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

networks:
  default:
    driver: bridge

# Optional: Add a database service if needed
# database:
#   image: postgres:13
#   environment:
#     - POSTGRES_USER=postgres
#     - POSTGRES_PASSWORD=postgres
#     - POSTGRES_DB=fraud_detection
#   ports:
#     - "5432:5432"
#   volumes:
#     - postgres_data:/var/lib/postgresql/data

volumes:
  # postgres_data: # Uncomment if database service is enabled 